### ISSUE TITLE
re-adopting after every docker restart?

### ISSUE THREAD

**Issue by RezzZ** [ryansch/docker-unifi-rpi#28]
Hi, just installed your docker on my pi3b+ but I keep having some problems. Every time my pi/docker container restarts (for development reasons) I need to re-adopt all my devices before I can control them. They stay on adopting otherwise after a restart of the container. I need to ssh into my devices to inform them of my new docker controller.
It seems some important settings are not persisted. Any thoughts?

I use a minor adjusted version from your compose file:

```
version: '2'
services:
  unifi:
    container_name: unifi
    image: ryansch/unifi-rpi:latest
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '6789:6789/tcp'
      - '8080:8080/tcp'
      - '8880:8880/tcp'
      - '8443:8443/tcp'
      - '8843:8843/tcp'
    volumes:
      - /opt/unifi/varlib:/var/lib/unifi
      - /opt/unifi/logs1:/usr/lib/unifi/logs
      - /opt/unifi/logs2:/var/log/unifi
      - /opt/unifi/run1:/usr/lib/unifi/run
      - /opt/unifi/run2:/run/unifi
      - /opt/unifi/work:/usr/lib/unifi/work
    restart: on-failure
    environment:
      - TZ=Europe/Amsterdam
```
