### ISSUE TITLE
cannot login after migration new sdcard rpi3b+

### ISSUE THREAD

**Issue by RezzZ** [ryansch/docker-unifi-rpi#34]
Hi, I just installed a new sd in my raspberry (3B+) and tried to restore my unifi installation. I backed up my opt/ folder and restored in on the new sd card. I created new images and containers for all my running docker applications. Unfortunately I cannot login to unifi, I get a:
```
Login error
Invalid username and/or password.
```

My compose file looks like this:

```
version: '2.1'
services:
  unifi:
    container_name: unifi
    image: ryansch/unifi-rpi:latest
    network_mode: "host"
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '6789:6789/tcp'
      - '8080:8080/tcp'
      - '8880:8880/tcp'
      - '8443:8443/tcp'
      - '8843:8843/tcp'
    volumes:
      - /opt/unifi/varlib:/var/lib/unifi
      - /opt/unifi/logs1:/usr/lib/unifi/logs
      - /opt/unifi/logs2:/var/log/unifi
      - /opt/unifi/run1:/usr/lib/unifi/run
      - /opt/unifi/run2:/run/unifi
      - /opt/unifi/work:/usr/lib/unifi/work
    restart: on-failure
    environment:
      - TZ=Europe/Amsterdam
```

Any ideas why my credentials are rejected? I already tried the default ubnt/ubnt but without luck
