### ISSUE TITLE
Failure to pull image of the stack: unify Pulling nog matching manifest for linux/arm/v7 . . 

### ISSUE THREAD

**Issue by pjdw** [ryansch/docker-unifi-rpi#98]
I have the unifi running in a container on a RPI4 which I watch with Diun. It triggered that there is an update. But when deploying my stack I get the above failure.
My stack code is:
```
version: '2'
services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: unless-stopped
    network_mode: host
    volumes:
``` 
etc
Is there a way to solve this?
